# Base image
FROM python:3.12

# Set working directory
WORKDIR /app

# Install required packages
RUN pip install fastapi uvicorn PyMuPDF python-multipart

# Expose the desired port
EXPOSE 8080

# Run the Python script on container startup
CMD uvicorn src.server:app --host $HOST --port 8080
