version: '3'

services:
  pdf_tools_server:
    build:
      dockerfile: Dockerfile.python
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
    ports:
      - 8080:8080
    volumes:
      - ./server/logs:/app/logs
      - ./server/src:/app/src
      - ./client-app/dist:/app/client
  npm_runner:
    build:
      dockerfile: Dockerfile.npm
    volumes:
      - ./client-app/dist:/app/client/dist
